# Generated by Django 5.2 on 2025-04-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('preset_type', models.CharField(choices=[('date_range', 'Date Range'), ('amount_filter', 'Amount Filter'), ('keyword', 'Keyword')])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-seperated keywords', null=True)),
                ('amount_value', models.FloatField(blank=True, null=True)),
                ('comparison_type', models.CharField(blank=True, choices=[('=', 'Equals'), ('lt', 'Greater Than'), ('gt', 'Less Than')], null=True)),
            ],
        ),
    ]
