# Generated by Django 5.2 on 2025-04-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preset',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
