# Generated by Django 5.2 on 2025-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_preset_end_date_alter_preset_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='comparison_type',
            field=models.CharField(blank=True, choices=[('=', 'Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than')], null=True),
        ),
    ]
